kibana:
  image: docker.elastic.co/kibana/kibana:6.3.2
  links:
    - elasticsearch:elasticsearch
  ports:
    - 5601:5601

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
  ports:
    - 9200:9200
    - 9300:9300
